title: How I ended up here
author: Jurgen Gjonçari
email: jurgen.gjoncari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I really don't have any ideas what to do.

# social links
twitter_username: jurgengjoncari # DO NOT include the @ character, or else the build will fail!
github_username:  jurgengjoncari # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
